/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('payloads').del()
  await knex('payloads').insert([
    {launch_id: 1, customer: 'US Space Force', mission: 'GPS', description: 'Launching the newest Block III GPS Satellite into MEO which will provide civilian and military GPS signals', classification: 'Unclassified'},
    {launch_id: 3, customer: 'SpaceX', mission: 'Starlink Group 5-10', description: `A batch of satellites for the Starlink mega-constellation - SpaceX's project for space-based Internet communication system.`, classification: 'Unclassified'},
    {launch_id: 2, customer: 'US Space Force', mission: 'SBIRS GEO-7', description: `An infrared sensing payload to detect missile launches`, classification: 'Secret'},
    {launch_id: 4, customer: "NRO", mission: "NROL-82", description: "Classified reconnaissance mission for the National Reconnaissance Office", classification: "Top Secret"},
    {launch_id: 5, customer: "US Space Force", mission: "AEHF-6", description: "Advanced Extremely High Frequency satellite to provide secure military communications", classification: "Secret"},
    {launch_id: 6, customer: "NRO", mission: "NROL-127", description: "Classified reconnaissance mission for the National Reconnaissance Office", classification: "Top Secret"},
    {launch_id: 7, customer: "Russian Federal Space Agency", mission: "Soyuz TM-14", description: "Classified reconnaissance mission for the Russian Federal Space Agency", classification: "Top Secret"},
    {launch_id: 8, customer: "US Space Force", mission: "SBIRS GEO-5", description: "Infrared sensing payload to detect missile launches", classification: "Secret"},
    {launch_id: 9, customer: "NASA", mission: "Artemis 3", description: "Returning humans to the moon in preparation for future Mars missions", classification: "Unclassified"},
    {launch_id: 10, customer: "ESA", mission: "JUICE", description: "A mission to explore Jupiter's icy moons", classification: "Unclassified"},
    {launch_id: 11, customer: "Boeing", mission: "Starliner-1", description: "Crewed test flight of Boeing's CST-100 Starliner spacecraft to the International Space Station", classification: "Unclassified"},
    {launch_id: 12, customer: "ISRO", mission: "Chandrayaan-3", description: "A lunar exploration mission to study the moon's south pole", classification: "Unclassified"},
    {launch_id: 13, customer: 'CASC', mission: 'Shenzhou-14', description: 'A crewed mission to the Chinese Space Station', classification: 'Unclassified'},
    {launch_id: 14, customer: 'CASC', mission: 'Tianwen-2', description: 'A Mars exploration mission to study the Martian geology, atmosphere, and environment', classification: 'Unclassified'},
    {launch_id: 15, customer: 'CASC', mission: 'Ziyuan-3 03', description: 'A high-resolution remote sensing satellite mission', classification: 'Unclassified'},
    {launch_id: 16, customer: 'CASC', mission: 'Yaogan-34', description: 'A group of three military reconnaissance satellites', classification: 'Secret'},
    {launch_id: 17, customer: "CNES", mission: "Taranis", description: "A mission to study the physics of lightning and its effects on the atmosphere", classification: "Unclassified"},
    {launch_id: 18, customer: "Rocket Lab", mission: "Photon First Light", description: "Demonstration flight of the Photon satellite platform", classification: "Unclassified"},
    {launch_id: 19, customer: "NASA", mission: "James Webb Space Telescope", description: "A space observatory to study the history of the universe", classification: "Unclassified"},
    {launch_id: 20, customer: "Spaceflight Inc.", mission: "Sherpa-FX1", description: "A demonstration flight of the Sherpa-FX1 orbital transfer vehicle", classification: "Unclassified"},
    {launch_id: 21, customer: "Roscosmos", mission: "Luna-25", description: "A Russian lunar lander mission to explore the moon's south pole", classification: "Unclassified"},
    {launch_id: 22, customer: 'CASC', mission: 'Change 7', description: 'A lunar exploration mission to collect samples from the Moon\'s south pole', classification: 'Unclassified'},
    {launch_id: 23, customer: "ESA", mission: "CHEOPS", description: "A space observatory to study exoplanet systems", classification: "Unclassified"},
    {launch_id: 24, customer: "Arianespace", mission: "Ariane 6 Test Flight", description: "Maiden flight of the Ariane 6 rocket", classification: "Unclassified"},
    {launch_id: 25, customer: "NASA", mission: "Mars Sample Return", description: "A mission to collect and return samples from Mars to Earth", classification: "Unclassified"},
    {launch_id: 26, customer: "Virgin Galactic", mission: "SpaceShipTwo Unity 23", description: "Suborbital flight carrying research payloads and private individuals", classification: "Unclassified"},
    {launch_id: 27, customer: "ISRO", mission: "Gaganyaan-1", description: "India's first crewed mission to space", classification: "Unclassified"},
    {launch_id: 28, customer: "ESA", mission: "Explorer-14", description: "Suborbital flight carrying research payloads and private individuals", classification: "Unclassified"},
    { launch_id: 29, customer: "NASA", mission: "Mars 2023", description: "Exploration mission to Mars", classification: "Top Secret" },
    { launch_id: 30, customer: "SpaceX", mission: "Starlink-26", description: "Deployment of 60 Starlink satellites into orbit", classification: "Unclassified" },
    { launch_id: 31, customer: "Roscosmos", mission: "ISS Expedition 67", description: "Crew rotation and resupply mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 32, customer: "Boeing", mission: "GPS III SV06", description: "Launch of GPS III satellite for the U.S. Space Force", classification: "Secret" },
    { launch_id: 33, customer: "ESA", mission: "JUICE", description: "JUpiter ICy moons Explorer mission to study Jupiter and its moons", classification: "Unclassified" },
    { launch_id: 34, customer: "Lockheed Martin", mission: "SBIRS GEO-5", description: "Launch of a missile early-warning satellite for the U.S. Space Force", classification: "Secret" },
    { launch_id: 35, customer: "SpaceX", mission: "Crew-4", description: "Crewed mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 36, customer: "Roscosmos", mission: "Luna 28", description: "Lunar sample-return mission", classification: "Top Secret" },
    { launch_id: 37, customer: "NASA", mission: "Europa Clipper", description: "Mission to study Jupiter's moon Europa", classification: "Unclassified" },
    { launch_id: 38, customer: "SpaceX", mission: "Transporter-2", description: "Deployment of multiple small payloads into sun-synchronous orbit", classification: "Unclassified" },
    { launch_id: 39, customer: "Boeing", mission: "Starliner-1", description: "Uncrewed test flight of the CST-100 Starliner spacecraft to the International Space Station", classification: "Unclassified" },
    { launch_id: 40, customer: "ISRO", mission: "Chandrayaan-3", description: "Lunar mission to study the moon's south pole region", classification: "Unclassified" },
    { launch_id: 41, customer: "SpaceX", mission: "Starlink-27", description: "Deployment of 60 Starlink satellites into orbit", classification: "Unclassified" },
    { launch_id: 42, customer: "JAXA", mission: "MMX", description: "Mars Moon eXploration mission to collect samples from Phobos", classification: "Secret" },
    { launch_id: 43, customer: "Roscosmos", mission: "Soyuz MS-22", description: "Crewed mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 44, customer: "NASA", mission: "Artemis 2", description: "Crewed mission to test the Orion spacecraft and the Lunar Gateway in lunar orbit", classification: "Top Secret" },
    { launch_id: 45, customer: "ESA", mission: "Euclid", description: "Cosmic Vision dark energy mission to study the geometry ofthe universe", classification: "Unclassified" },
    { launch_id: 46, customer: "SpaceX", mission: "Falcon Heavy Demo-2", description: "Test flight of the Falcon Heavy rocket with a dummy payload", classification: "Unclassified" },
    { launch_id: 47, customer: "NASA", mission: "Lunar Flashlight", description: "Lunar orbiter to search for water ice on the moon", classification: "Secret" },
    { launch_id: 48, customer: "Boeing", mission: "NSSL-2", description: "Launch of a classified national security satellite for the U.S. Space Force", classification: "Top Secret" },
    { launch_id: 49, customer: "Roscosmos", mission: "Soyuz MS-23", description: "Crewed mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 50, customer: "NASA", mission: "Mars Sample Return", description: "Mission to collect and return samples from Mars", classification: "Top Secret" },
    { launch_id: 51, customer: "SpaceX", mission: "Starlink-28", description: "Deployment of 60 Starlink satellites into orbit", classification: "Unclassified" },
    { launch_id: 52, customer: "ESA", mission: "Hera", description: "Asteroid impact mission to study the Didymos binary asteroid system", classification: "Secret" },
    { launch_id: 53, customer: "NASA", mission: "Dragonfly", description: "Mission to explore Saturn's moon Titan using a drone", classification: "Unclassified" },
    { launch_id: 54, customer: "Roscosmos", mission: "Luna 29", description: "Lunar lander mission to study the moon's south pole region", classification: "Top Secret" },
    { launch_id: 55, customer: "SpaceX", mission: "GPS III SV07", description: "Launch of GPS III satellite for the U.S. Space Force", classification: "Secret" },
    { launch_id: 56, customer: "Boeing", mission: "Starliner-2", description: "Crewed test flight of the CST-100 Starliner spacecraft to the International Space Station", classification: "Unclassified" },
    { launch_id: 57, customer: "NASA", mission: "Wide Field Infrared Survey Telescope (WFIRST)", description: "Mission to study dark matter and dark energy", classification: "Unclassified" },
    { launch_id: 58, customer: "SpaceX", mission: "Transporter-3", description: "Deployment of multiple small payloads into sun-synchronous orbit", classification: "Unclassified" },
    { launch_id: 59, customer: "Roscosmos", mission: "Soyuz MS-24", description: "Crewed mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 60, customer: "ESA", mission: "Aurora", description: "Manned mission to the moon", classification: "Top Secret" },
    { launch_id: 61, customer: "NASA", mission: "Europa Clipper", description: "Mission to study Jupiter's icy moon Europa", classification: "Unclassified" },
    { launch_id: 62, customer: "SpaceX", mission: "Starship Orbital Test", description: "Test flight of the Starship spacecraft in Earth orbit", classification: "Unclassified" },
    { launch_id: 63, customer: "Boeing", mission: "X-37B OTV-7", description: "Unmanned test flight of the X-37B spaceplane for the U.S. Air Force", classification: "Top Secret" },
    { launch_id: 64, customer: "Roscosmos", mission: "Spektr-RG", description: "X-ray observatory mission to study black holes and galaxy clusters", classification: "Unclassified" },
    { launch_id: 65, customer: "NASA", mission: "Psyche", description: "Mission to study the metal asteroid Psyche", classification: "Secret" },
    { launch_id: 66, customer: "SpaceX", mission: "Starlink-29", description: "Deployment of 60 Starlink satellites into orbit", classification: "Unclassified" },
    { launch_id: 67, customer: "ESA", mission: "JUICE", description: "Mission to study Jupiter and its icy moons", classification: "Secret" },
    { launch_id: 68, customer: "NASA", mission: "NISAR", description: "Radar imaging satellite mission to study Earth's surface", classification: "Top Secret" },
    { launch_id: 69, customer: "Roscosmos", mission: "Luna 30", description: "Lunar lander mission to study the moon's south pole region", classification: "Secret" },
    { launch_id: 70, customer: "SpaceX", mission: "Crew-3", description: "Crewed mission to the International Space Station", classification: "Unclassified" },
    { launch_id: 71, customer: "Boeing", mission: "NSSL-3", description: "Launch of a classified national security satellite for the U.S. Space Force", classification: "Top Secret" },
    { launch_id: 72, customer: "NASA", mission: "Voyager Interstellar Mission", description: "Mission to study the outer reaches of the Solar System and interstellar space", classification: "Unclassified" },
    { launch_id: 73, customer: "SpaceX", mission: "Starship Lunar Test", description: "Test flight of the Starship spacecraft to the moon", classification: "Unclassified" },
    { launch_id: 74, customer: "Roscosmos", mission: "Fobos-Grunt 2", description: "Mission to study the Martian moon Phobos", classification: "Secret" },
    { launch_id: 75, customer: "NASA", mission: "Wide-Field Space Telescope", description: "Space telescope mission to study dark energy and exoplanets", classification: "Unclassified" },
    { launch_id: 76, customer: "SpaceX", mission: "SES-18/GovSat-1B", description: "Launch of a communications satellite for SES and the Luxembourg government", classification: "Unclassified" },
    { launch_id: 77, customer: "ESA", mission: "BepiColombo", description: "Mission to study Mercury", classification: "Secret" },
    { launch_id: 78, customer: "NASA", mission: "Dragonfly", description: "Mission to study Saturn's moon Titan with a drone", classification: "Secret" },
    { launch_id: 79, customer: "Roscosmos", mission: "Interhelio-Zond", description: "Mission to study the Sun and space weather", classification: "Top Secret" },
    { launch_id: 80, customer: "Children Around the World", mission: "X-MAS 23", description: "Mission to deliver presents to good boys and girls", classification: "Top Secret" },
  ]);
};
